### ISSUE TITLE
MCM Menu Just Says "Installed"

### ISSUE THREAD

**Issue by swalp1** [Neanka/MCM_0.1_AS3#89]
When i try to open the mcm, the spot for it just says "Installed" and clicking on it just gives a bunch of lookup failed errors. I'm using vortex and have the correct versions of f4se and mcm installed. I have also tried re-installing both but neither worked.
![20241219014852_1](https://github.com/user-attachments/assets/0d4e55ff-6fd4-46bb-905a-b64bd478c6fc)
![20241219014855_1](https://github.com/user-attachments/assets/eafd92d9-8a36-477e-9bb4-87597a071d8e)

**Comment by swalp1** [comment]
nevermind im blind its something else

**Comment by swalp1** [comment]
no idea what this menu is then

**Comment by Hetamax** [comment]
I have the same issue but I don't have the Mod Config, it just says installed and lookup failed. Were you ever able to figure out what happened?

EDIT: I FIGURED IT OUT! The issue is Fallout 4 updated to version 1.10.984 and the stable version of MCM is currently built for version 1.10.163. The Beta version however is built for version 1.10.984 so that's what the "INSTALLED" Thing is, it's the "stable" version that is built for the last version of Fallout 4.

EDIT 2: Okay so I just checked and the Beta version also has the "INSTALLED" issue but at least the mod is working now.
